### ISSUE TITLE
Mac installation error

### ISSUE THREAD

**Issue by terna** [Repast/repast4py#18]
env CC=mpicxx pip3 install repast4py
starts, but ends with
  Building wheel for repast4py (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:

The whole error message is reported in the attachment.

Best, Pietro
[err.pdf](https://github.com/Repast/repast4py/files/7456620/err.pdf)

**Comment by terna** [comment]
I tried to run anything in a fresh installation of Macport, but the effect is the same. Best, Pietro

**Comment by ncollier** [comment]
Thanks for reporting the issue. We are looking into it now.

**Comment by ncollier** [comment]
Fixed in 3537a4c

Reproduced issue and tested fix under macOS 11.3.1 with openmpi-4.1.1 compiled from source, and `export TMPDIR=/tmp` to work around issue openmpi has with macOS' really long tmp directory names. I also had to user the openmpi flag `oversubscribe` to run the tests, as openmpi wants to use only the number of cores by default.

` mpirun --oversubscribe -n 9 python -m unittest tests.shared_vl_tests` 

`repast4py-1.0.3b1.tar.gz` was pushed to PyPI.

@terna Can you try to pip install repast4py again. You may need the -U argument to install 1.0.3b1 rather than the cached 1.0.2b1. 

` env CC=mpicxx pip install -U repast4py`
